apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: embarrassed-baboon-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: embarrassed-baboon-go 
  name: embarrassed-baboon-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: embarrassed-baboon-go 
